---
title: "Data Mining with R"
author: "Somto Momah"
date: "1/18/2020"
output: pdf_document
---
#Libraries
```{r}
library('tidytext')
library('dplyr')
library('stringr')
library('janeaustenr')
library('ggplot2')
library('gutenbergr')
library('scales')
library('tidyverse')
```
        
```{r}
text<-c("Nobody, Absolute nobdoy", "Tayo: Flutter is the best language in the world", "All the lengthy lines of code in Java can be summarised in a lIne in flutter", "Me: Pele, flutter advocate of Nigeria")
text
```

#Connverting to a tibble
```{r}
text_tb<- tibble(line= 1:4, text = text)
text_tb
```

```{r}
text_tb %>% unnest_tokens(word, text)
```
#Tidying the work of Jane Austen
```{r}
jane_books <-austen_books() %>% group_by(book) %>% mutate(linenumber = row_number(), chapter = cumsum(str_detect(text, regex("^chapter[\\divxlc]", ignore_case = TRUE)))) %>% ungroup()
 jane_books
```

```{r}
tidy_books <-jane_books %>% unnest_tokens(word, text)
tidy_books
```

```{r}
data("stop_words")
tidy_books <- tidy_books %>% anti_join(stop_words)
```
```{r}
tidy_books %>% count(word, sort = TRUE)
```
```{r}
tidy_books %>% count(word, sort = TRUE) %>%
  filter(n>600) %>% mutate(word = reorder(word,n)) %>% ggplot(aes(word, n)) + geom_col() + xlab(NULL) + coord_flip()
```

```{r}
hgwells<-gutenberg_download(c(35, 36, 5230, 159))
```



```{r}
tidy_hgwells<- hgwells %>% unnest_tokens(word, text) %>% anti_join(stop_words)
```

```{r}
tidy_hgwells %>% count(word, sort= TRUE)
```
```{r}
bronte <- gutenberg_download(c(1260, 768, 969, 9182, 767))
```

```{r}
tidy_bronte <- bronte %>% unnest_tokens(word, text) %>% anti_join(stop_words)
```
```{r}
tidy_bronte %>% count(word, sort = TRUE)
```

```{r}
library(tidyr)

frequency <- bind_rows(mutate(tidy_bronte, author = "Brontë Sisters"),
                       mutate(tidy_hgwells, author = "H.G. Wells"), 
                       mutate(tidy_books, author = "Jane Austen")) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>%
  count(author, word) %>%
  group_by(author) %>%
  mutate(proportion = n / sum(n)) %>% 
  select(-n) %>% 
  spread(author, proportion) %>% 
  gather(author, proportion, `Brontë Sisters`:`H.G. Wells`)
```

```{r}
library(scales)

# expect a warning about rows with missing values being removed
ggplot(frequency, aes(x = proportion, y = `Jane Austen`, color = abs(`Jane Austen` - proportion))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  scale_color_gradient(limits = c(0, 0.001), low = "darkslategray4", high = "gray75") +
  facet_wrap(~author, ncol = 2) +
  theme(legend.position="none") +
  labs(y = "Jane Austen", x = NULL)
```
  
```{r}
cor.test(data = frequency[frequency$author == "Brontë Sisters",],
         ~ proportion + `Jane Austen`)
```

```{r}
cor.test(data = frequency[frequency$author == "H.G. Wells",], 
         ~ proportion + `Jane Austen`)
```
#Sentiment Analysis (Sentiment data sets)
```{r}
get_sentiments("afinn")
get_sentiments("bing")
get_sentiments("nrc")
```
